version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies.."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws s3 cp --recursive deployment_package.zip s3://lambdabucketwipo/lambda/
      - aws lambda update-function-code --function-name Lambdafucntiontest --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
